import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import {
  Zap,
  ArrowRight,
  Battery,
  ArrowLeftRight,
  ShieldCheck,
  Radio,
  Cpu,
  SunMedium,
  Moon,
} from 'lucide-react';
import { useTheme } from '../context/ThemeContext';
import { useGrid } from '../context/GridContext';
import MicrogridVisualization from '../components/MicrogridVisualization';

const SHARING_TIERS = [
  {
    step: '01',
    name: 'Peer-to-Peer Routing',
    priority: 'Primary Tier',
    desc: 'Surplus solar generated by any building is routed directly to neighboring deficit buildings over campus microgrid interconnects with zero transmission leakage.',
    icon: ArrowLeftRight,
  },
  {
    step: '02',
    name: 'Shared Storage Buffer',
    priority: 'Secondary Tier',
    desc: 'When local peer demand is satisfied, surplus charges the 100 kWh shared BESS battery, buffering daytime solar peaks to discharge during campus-wide deficits.',
    icon: Battery,
  },
  {
    step: '03',
    name: 'Utility Grid Coupling',
    priority: 'Bounded Last Resort',
    desc: 'Main utility power is drawn strictly when all local generation and battery reserves are depleted, preserving self-sufficiency and mitigating grid tariff exposure.',
    icon: Radio,
  },
];

const PIPELINE_STEPS = [
  {
    num: '01',
    title: 'Physical Ingestion',
    detail: 'Continuous telemetry monitors real-time solar generation, facility load, and local battery SoC across all 5 substations.',
  },
  {
    num: '02',
    title: 'Policy Reasoning',
    detail: 'Gemini 2.5 Flash evaluates microgrid state to synthesize optimal peer-to-peer and battery routing plans.',
  },
  {
    num: '03',
    title: 'Invariant Verification',
    detail: 'Authoritative reservation contracts enforce strict conservation of energy without mutating immutable physical telemetry.',
  },
  {
    num: '04',
    title: 'Deterministic Safety',
    detail: 'Under grid failure or connectivity loss, deterministic rulebooks guarantee uninterrupted campus power stability.',
  },
];

export default function LandingPage() {
  const navigate = useNavigate();
  const { isDark, toggleTheme } = useTheme();
  const { state } = useGrid();

  const buildings = state?.buildings || [
    { buildingId: 'b01', name: 'Science Hub', shortName: 'B01', solarGeneration: 8.5, consumption: 5.4, batteryLevel: 75, status: 'SURPLUS', energyBalance: 3.1 },
    { buildingId: 'b02', name: 'Admin Block', shortName: 'B02', solarGeneration: 2.1, consumption: 6.8, batteryLevel: 45, status: 'DEFICIT', energyBalance: -4.7 },
    { buildingId: 'b03', name: 'Library & Media', shortName: 'B03', solarGeneration: 4.2, consumption: 4.0, batteryLevel: 60, status: 'BALANCED', energyBalance: 0.2 },
    { buildingId: 'b04', name: 'Student Center', shortName: 'B04', solarGeneration: 1.8, consumption: 7.2, batteryLevel: 30, status: 'DEFICIT', energyBalance: -5.4 },
    { buildingId: 'b05', name: 'Engineering Hall', shortName: 'B05', solarGeneration: 9.6, consumption: 4.8, batteryLevel: 80, status: 'SURPLUS', energyBalance: 4.8 },
  ];

  const rawBattery = state?.centralBattery;
  const batteryPct = typeof rawBattery === 'object' && rawBattery !== null
    ? Number(rawBattery.percentage ?? rawBattery.batteryLevel ?? 0)
    : (typeof rawBattery === 'number' ? rawBattery : 68);

  const gridCore = state
    ? {
        ...state,
        centralBattery: batteryPct,
        percentage: batteryPct,
      }
    : {
        percentage: 68,
        centralBattery: 68,
        energyBalance: -2.0,
        mainGrid: { online: true, powerImported: 2.0 },
        gridStatus: 'GRID ONLINE',
      };

  const activeTransfers = state?.activeTransfers || [
    { from: 'b05', to: 'b02', amount: 1.5, type: 'P2P' },
    { from: 'b01', to: 'b04', amount: 1.2, type: 'P2P' },
  ];

  return (
    <div className="min-h-[100dvh] flex flex-col bg-[var(--bg-page)] text-[var(--text-primary)] transition-colors duration-400">
      {/* ── Quiet Top Header ── */}
      <header
        className="sticky top-0 z-50 w-full border-b backdrop-blur-xl transition-colors duration-400"
        style={{
          backgroundColor: isDark ? 'rgba(16, 17, 20, 0.82)' : 'rgba(246, 245, 241, 0.88)',
          borderColor: 'var(--border-subtle)',
        }}
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-8 h-14 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2.5 interactive-tap">
            <div
              className="w-6 h-6 rounded-md flex items-center justify-center"
              style={{
                backgroundColor: 'var(--accent-primary)',
                color: isDark ? '#101114' : '#ffffff',
              }}
            >
              <Zap size={13} className="fill-current" />
            </div>
            <div className="flex items-baseline gap-2">
              <span className="font-medium text-sm tracking-tight text-[var(--text-primary)]">
                GridShare
              </span>
              <span className="hidden sm:inline text-[9px] uppercase font-mono tracking-[0.16em] text-[var(--text-muted)]">
                EMS
              </span>
            </div>
          </Link>

          <div className="flex items-center gap-4">
            <button
              onClick={toggleTheme}
              aria-label="Toggle theme"
              className="w-7 h-7 rounded-md flex items-center justify-center transition-all duration-150 cursor-pointer interactive-tap border border-[var(--border-subtle)] hover:border-[var(--border-default)] text-[var(--text-muted)] hover:text-[var(--text-primary)]"
              style={{
                backgroundColor: isDark ? 'rgba(255, 255, 255, 0.02)' : 'rgba(0, 0, 0, 0.02)',
              }}
            >
              {isDark ? (
                <SunMedium size={14} className="text-[var(--accent-primary)]" />
              ) : (
                <Moon size={14} className="text-[var(--text-secondary)]" />
              )}
            </button>

            <button
              onClick={() => navigate('/dashboard')}
              className="flex items-center gap-2 px-3.5 py-1.5 rounded-md text-xs font-medium transition-all duration-150 cursor-pointer interactive-tap shadow-sm"
              style={{
                backgroundColor: 'var(--accent-primary)',
                color: isDark ? '#101114' : '#ffffff',
              }}
            >
              <span>Workstation</span>
              <ArrowRight size={12} />
            </button>
          </div>
        </div>
      </header>

      {/* ── Section 1: Asymmetric Hero with Living Microgrid Topology ── */}
      <section className="relative overflow-hidden py-16 sm:py-28 border-b border-[var(--border-subtle)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-8 relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center">
            {/* Left: Editorial Statement & Storytelling */}
            <div className="lg:col-span-5 flex flex-col items-start text-left">
              <div className="flex items-center gap-2.5 mb-5">
                <span className="w-1.5 h-1.5 rounded-full bg-[var(--accent-primary)] animate-network-breathe" />
                <span className="text-eyebrow">
                  Decentralized Campus EMS
                </span>
              </div>

              <h1 className="text-display text-[var(--text-primary)] mb-6">
                Autonomous energy coordination.
              </h1>

              <p className="text-body-lg text-[var(--text-secondary)] mb-10 max-w-[46ch]">
                GridShare orchestrates solar generation, facility loads, and central battery storage across 5 campus substations—optimizing dispatch in real time with physical telemetry integrity.
              </p>

              <div className="flex flex-wrap items-center gap-4 w-full sm:w-auto">
                <button
                  onClick={() => navigate('/dashboard')}
                  className="flex items-center justify-center gap-2 px-6 py-2.5 rounded-md text-xs font-medium transition-all duration-150 cursor-pointer interactive-tap shadow-sm"
                  style={{
                    backgroundColor: 'var(--accent-primary)',
                    color: 'var(--accent-contrast)',
                  }}
                >
                  <span>Launch Operations Console</span>
                  <ArrowRight size={13} />
                </button>

                <button
                  onClick={() => {
                    const el = document.getElementById('dispatch-hierarchy');
                    if (el) el.scrollIntoView({ behavior: 'smooth' });
                  }}
                  className="flex items-center justify-center gap-2 px-4 py-2.5 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors cursor-pointer"
                >
                  <span>Dispatch Hierarchy</span>
                  <ArrowRight size={12} className="opacity-60" />
                </button>
              </div>

              {/* Physical Assurance Markers (Quiet & Understated) */}
              <div className="flex items-center gap-6 mt-14 pt-6 border-t border-[var(--border-subtle)] w-full text-xs text-[var(--text-muted)]">
                <div className="flex items-center gap-2">
                  <ShieldCheck size={13} className="text-[var(--text-secondary)]" />
                  <span>Physics Verified</span>
                </div>
                <div className="flex items-center gap-2">
                  <Cpu size={13} />
                  <span>Gemini 2.5 Agent</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-[var(--status-surplus)]" />
                  <span>Deterministic Fallback</span>
                </div>
              </div>
            </div>

            {/* Right: Living Spatial Topology Hero Object (Unboxed & Integrated) */}
            <div className="lg:col-span-7 w-full">
              <div className="aspect-[16/10] w-full relative">
                <MicrogridVisualization
                  buildings={buildings}
                  gridCore={gridCore}
                  activeTransfers={activeTransfers}
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Section 2: Three-Tier Dispatch Architecture (Unboxed Architectural Columns) ── */}
      <section id="dispatch-hierarchy" className="py-24 sm:py-32 border-b border-[var(--border-subtle)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-8">
          <div className="max-w-2xl mb-18">
            <span className="text-eyebrow block mb-3">
              Dispatch Architecture
            </span>
            <h2 className="text-title-lg text-[var(--text-primary)]">
              Three-Tier Energy Routing Hierarchy
            </h2>
            <p className="text-body text-[var(--text-secondary)] mt-3">
              Energy is conserved through an unambiguous physical priority order that maximizes local utilization before drawing supplementary grid power.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            {SHARING_TIERS.map(({ step, name, priority, desc, icon: Icon }) => (
              <div
                key={step}
                className="pt-6 border-t border-[var(--border-subtle)] flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-xs font-mono text-[var(--text-muted)]">Tier {step}</span>
                    <Icon size={14} className="text-[var(--text-muted)]" />
                  </div>
                  <span className="text-[11px] text-[var(--text-muted)] block mb-4">
                    {priority}
                  </span>

                  <h3 className="text-title-sm text-[var(--text-primary)] mb-2.5 font-medium">
                    {name}
                  </h3>
                  <p className="text-body-sm text-[var(--text-secondary)] leading-relaxed">
                    {desc}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Section 3: Autonomous Intelligence Pipeline (Unboxed Step Progression) ── */}
      <section className="py-24 sm:py-32 border-b border-[var(--border-subtle)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-8">
          <div className="max-w-2xl mb-18">
            <span className="text-eyebrow block mb-3">
              Orchestration Engine
            </span>
            <h2 className="text-title-lg text-[var(--text-primary)]">
              Observe · Reason · Reserve · Verify
            </h2>
            <p className="text-body text-[var(--text-secondary)] mt-3">
              High-level policy reasoning is decoupled from physical invariants: Gemini 2.5 Flash synthesizes optimal routing strategies while an authoritative accounting layer enforces conservation of energy.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            {PIPELINE_STEPS.map(({ num, title, detail }) => (
              <div
                key={num}
                className="pt-6 border-t border-[var(--border-subtle)]"
              >
                <span className="text-xs font-mono text-[var(--text-muted)] block mb-3">
                  Phase {num}
                </span>
                <h4 className="text-sm font-medium text-[var(--text-primary)] mb-2">
                  {title}
                </h4>
                <p className="text-body-sm text-[var(--text-secondary)] leading-relaxed">
                  {detail}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Section 4: Call To Action (Quiet & Editorial) ── */}
      <section className="py-28 sm:py-36">
        <div className="max-w-3xl mx-auto px-4 sm:px-8 text-center">
          <span className="text-eyebrow block mb-3">Operations Workstation</span>
          <h2 className="text-display text-[var(--text-primary)] mb-4">
            Live Microgrid Control
          </h2>
          <p className="text-body-lg text-[var(--text-secondary)] max-w-lg mx-auto mb-10">
            Inspect real-time telemetry across 5 campus buildings, evaluate storage buffering, dispatch AI routing cycles, and audit settled energy ledgers.
          </p>
          <button
            onClick={() => navigate('/dashboard')}
            className="inline-flex items-center gap-2 px-7 py-3 rounded-md text-xs font-medium transition-all duration-150 cursor-pointer interactive-tap shadow-sm"
            style={{
              backgroundColor: 'var(--accent-primary)',
              color: 'var(--accent-contrast)',
            }}
          >
            <span>Launch Operations Console</span>
            <ArrowRight size={13} />
          </button>
        </div>
      </section>

      {/* ── Editorial Footer ── */}
      <footer className="border-t border-[var(--border-subtle)] py-8 text-xs text-[var(--text-muted)]">
        <div className="max-w-7xl mx-auto px-4 sm:px-8 flex flex-col sm:flex-row items-center justify-between gap-4 font-mono">
          <div className="flex items-center gap-2">
            <span className="font-medium text-[var(--text-primary)] font-sans">GridShare</span>
            <span>· Campus Microgrid EMS</span>
          </div>
          <div className="flex items-center gap-6 text-[11px]">
            <Link to="/dashboard" className="hover:text-[var(--text-primary)] transition-colors">Overview</Link>
            <Link to="/buildings" className="hover:text-[var(--text-primary)] transition-colors">Substations</Link>
            <Link to="/ai-decisions" className="hover:text-[var(--text-primary)] transition-colors">Decisions</Link>
            <Link to="/transactions" className="hover:text-[var(--text-primary)] transition-colors">Ledger</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
